Fix daily build failure
OpenLiberty/guide-graphql-client pull request #38
Opened 2022-09-15 14:15 UTC by shin19991207

2022-09-15 14:30 UTC, shin19991207 commented
Daily build passed at https://github.com/OpenLiberty/guides-common/actions/runs/3061189651

2022-09-15 16:47 UTC, gkwan-ibm requested changes
hi @shin19991207 

`sed -i "s;FROM icr.io/appcafe/open-liberty:full-${JAVA_VERSION} ...` does not work. You can check the daily build log.

Suggest to replace `$`, `{`, and `}` by `.` as
`sed -i "s;FROM icr.io/appcafe/open-liberty:full-..JAVA_VERSION. ...`

2022-09-16 16:14 UTC, gkwan-ibm requested changes
hi @shin19991207 

This line is not right.
```
sed -i "s;FROM $DOCKER_USERNAME/olguides:$BUILD;g" system/Dockerfile graphql/Dockerfile query/Dockerfile
```
It should be
```
sed -i "s;FROM icr.io/appcafe/open-liberty:full-..JAVA_VERSION.-openj9-ubi;FROM $DOCKER_USERNAME/olguides:$BUILD;g" system/Dockerfile graphql/Dockerfile query/Dockerfile
```

2022-09-16 19:17 UTC, gkwan-ibm approved these changes

2022-09-16 19:31 UTC, merged