Version update
OpenLiberty/guide-graphql-client pull request #4
Opened 2022-01-26 15:58 UTC by priyyanshi

Updating dependency versions and artifactid.

2022-01-27 20:39 UTC, gkwan-ibm approved these changes
- **Replace the server configuration file.**
  - [ ] server.xml not highlight/focus correctly

2022-01-27 20:40 UTC, gkwan-ibm requested changes
- **Replace the server configuration file.**
  - [ ] server.xml not highlight/focus correctly 
- [ ] because it is a new guide and not published yet, all license year should be  `2022` only instead of `2021, 2022`. Update both draft-1 and verson-update branches
- [ ] "GraphQL service" -> "`graphql` microservice" if referring to the `graphql` microservice under the `graphql` directory

2022-06-22 18:22 UTC, t27gupta approved these changes

2022-06-22 18:23 UTC, gkwan-ibm approved these changes

2022-06-22 18:24 UTC, merged